-- Create CDC source table (updated for padded GDELT dataset)
CREATE TABLE IF NOT EXISTS gdelt_cdc_source (
    globaleventid BIGINT,
    event_date INT,
    source_country STRING,
    target_country STRING,
    cameo_code STRING,
    num_events INT,
    num_articles INT,
    quad_class INT,
    goldstein_scale DOUBLE,
    source_geo_type INT,
    source_geo_lat DOUBLE,
    source_geo_long DOUBLE,
    target_geo_type INT,
    target_geo_lat DOUBLE,
    target_geo_long DOUBLE,
    action_geo_type INT,
    action_geo_lat DOUBLE,
    action_geo_long DOUBLE,
    event_time TIMESTAMP(3),
    last_updated TIMESTAMP(3),
    PRIMARY KEY (globaleventid) NOT ENFORCED
) WITH (
    'connector' = 'postgres-cdc',
    'hostname' = 'postgres',
    'port' = '5432',
    'username' = 'flink_user',
    'password' = 'flink_pass',
    'database-name' = 'gdelt',
    'schema-name' = 'public',
    'table-name' = 'gdelt_events',
    'slot.name' = 'gdelt_flink_slot',
    'debezium.snapshot.mode' = 'never',
    'debezium.publication.name' = 'gdelt_flink_pub',
    'debezium.publication.autocreate.mode' = 'filtered',
    'debezium.slot.drop.on.stop' = 'false',
    'decoding.plugin.name' = 'pgoutput',
    'changelog-mode' = 'all'
);
