-- Baseline database - for performance comparison
-- This has the SAME data as main postgres, but NO Flink processing

CREATE TABLE IF NOT EXISTS gdelt_events (
    globaleventid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_date INT NOT NULL,
    source_actor TEXT NOT NULL,
    target_actor TEXT NOT NULL,
    cameo_code TEXT NOT NULL,
    num_events INT NOT NULL,
    num_articles INT NOT NULL,
    quad_class INT NOT NULL,
    goldstein DOUBLE PRECISION,
    source_geo_type INT,
    source_geo_lat DOUBLE PRECISION,
    source_geo_long DOUBLE PRECISION,
    target_geo_type INT,
    target_geo_lat DOUBLE PRECISION,
    target_geo_long DOUBLE PRECISION,
    action_geo_type INT,
    action_geo_lat DOUBLE PRECISION,
    action_geo_long DOUBLE PRECISION
);

-- Indexes (same as main)
CREATE INDEX IF NOT EXISTS idx_baseline_event_date ON gdelt_events(event_date);
CREATE INDEX IF NOT EXISTS idx_baseline_source_actor ON gdelt_events(source_actor);
CREATE INDEX IF NOT EXISTS idx_baseline_target_actor ON gdelt_events(target_actor);
CREATE INDEX IF NOT EXISTS idx_baseline_cameo_code ON gdelt_events(cameo_code);
CREATE INDEX IF NOT EXISTS idx_baseline_quad_class ON gdelt_events(quad_class);

-- Grant permissions
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO flink_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO flink_user;

-- Sample data (minimal)
INSERT INTO gdelt_events (
  event_date, source_actor, target_actor, cameo_code,
  num_events, num_articles, quad_class, goldstein
) VALUES
  (20240115, 'USA', 'CHN', '043', 1, 5, 3, -2.5),
  (20240115, 'GBR', 'FRA', '010', 1, 3, 1, 4.5),
  (20240115, 'RUS', 'UKR', '190', 2, 12, 4, -8.0);

SELECT 'Baseline database initialized!' as status;
