
-- Global Conflict Monitoring - Source Schema

-- Source table (raw events)
CREATE TABLE IF NOT EXISTS gdelt_events (
    globaleventid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_date INT NOT NULL,              -- yyyymmdd (e.g., 19790101)
    source_actor TEXT NOT NULL,
    target_actor TEXT NOT NULL,
    cameo_code TEXT NOT NULL,

    num_events INT NOT NULL,
    num_articles INT NOT NULL,            -- from NumArts in file
    quad_class INT NOT NULL,
    goldstein DOUBLE PRECISION,           -- can be NULL

    source_geo_type INT,
    source_geo_lat DOUBLE PRECISION,
    source_geo_long DOUBLE PRECISION,

    target_geo_type INT,
    target_geo_lat DOUBLE PRECISION,
    target_geo_long DOUBLE PRECISION,

    action_geo_type INT,
    action_geo_lat DOUBLE PRECISION,
    action_geo_long DOUBLE PRECISION
);

-- Helpful indexes for common queries
CREATE INDEX IF NOT EXISTS idx_gdelt_event_date ON gdelt_events(event_date);
CREATE INDEX IF NOT EXISTS idx_gdelt_source_actor ON gdelt_events(source_actor);
CREATE INDEX IF NOT EXISTS idx_gdelt_target_actor ON gdelt_events(target_actor);
CREATE INDEX IF NOT EXISTS idx_gdelt_cameo_code ON gdelt_events(cameo_code);
CREATE INDEX IF NOT EXISTS idx_gdelt_quad_class ON gdelt_events(quad_class);

-- Minimal sample rows for smoke testing
INSERT INTO gdelt_events (
  globaleventid, event_date, source_actor, target_actor, cameo_code,
  num_events, num_articles, quad_class, goldstein,
  source_geo_type, source_geo_lat, source_geo_long,
  target_geo_type, target_geo_lat, target_geo_long,
  action_geo_type, action_geo_lat, action_geo_long
) VALUES
  (1, 19790101, 'AFR', 'FRA',    '043', 1, 4, 1,  2.8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (2, 19790101, 'AFR', 'FRA',    '050', 2, 9, 1,  3.5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (3, 19790101, 'ARG', 'CHL',    '172', 2, 4, 4, -5.0, 1, -34, -64, 1, -30, -71, 1, -34, -64),
  (4, 19790101, 'CHN', 'CHNGOV', '0841', 1, 6, 2,  7.0, 4, 39.9289, 116.388, 4, 39.9289, 116.388, 4, 39.9289, 116.388)
ON CONFLICT (globaleventid) DO NOTHING;

-- Grant permissions to Flink user
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO flink_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO flink_user;

-- Enable CDC on the source table
ALTER TABLE gdelt_events REPLICA IDENTITY FULL;

-- Confirmation
SELECT
  'Database schema initialized successfully!' AS status,
  (SELECT COUNT(*) FROM gdelt_events) AS sample_events;
